### ISSUE TITLE
Hello cann't we use slider with this cool timeline plugin 

### ISSUE THREAD

**Issue by keshav1990** [icambron/timestack#5] opened 2017-04-22 13:54 UTC
http://prntscr.com/ezi3bg

Like have problem with this

**Comment by icambron** [comment] 2017-04-22 15:24
Not sure how I can help? It looks like there might be conflicting styles? You'll have to give me something I can reproduce.

**Comment by icambron** [comment] 2017-04-24 20:36
Closing for now

**Closed as completed by icambron** 2017-04-24 20:36 UTC

**Comment by keshav1990** [comment] 2017-04-26 07:29
Like you have timeline for specific time with static cannt we make it scrollable till week end
